version: '3.8'

services:
  app:
    image: "thevahidal/hoopoe:${TAG}"
    command: python manage.py migrate && gunicorn hoopoe.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env.prod
    network_mode: host

  celery:
    image: "thevahidal/hoopoe:${TAG}"
    command: /bin/sh -c "/home/app/web/entrypoint.prod.celery.sh"
    restart: on-failure
    env_file:
      - .env.prod
    depends_on:
      - app
    network_mode: host

  celery-beat:
    image: "thevahidal/hoopoe:${TAG}"
    command: /bin/sh -c "/home/app/web/entrypoint.prod.beat.sh"
    restart: on-failure
    env_file:
      - .env.prod
    depends_on:
      - app
    network_mode: host

  telegram-client:
    image: "thevahidal/hoopoe:${TAG}"
    command: /bin/sh -c "/home/app/web/entrypoint.prod.telegram.sh"
    restart: on-failure
    env_file:
      - .env.prod
    depends_on:
      - app
    network_mode: host