version: '3.8'

services:
  app:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env.prod
    depends_on:
      - db
    networks:
      - local_network

  db:
    image: postgres:13.0-alpine
    hostname: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod
    networks:
      - local_network

volumes:
  postgres_data:

networks:
  local_network: