version: '3.8'

services:
  app:
    image: "thevahidal/hoopoe:${TAG}"
    command: gunicorn hoopoe.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env.prod
    extra_hosts:
      - "host.docker.internal:host-gateway"

  celery:
    image: "thevahidal/hoopoe:${TAG}"
    command: /bin/sh -c "/home/app/web/entrypoint.prod.celery.sh"
    restart: on-failure
    env_file:
      - .env.prod
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  celery-beat:
    image: "thevahidal/hoopoe:${TAG}"
    command: /bin/sh -c "/home/app/web/entrypoint.prod.beat.sh"
    restart: on-failure
    env_file:
      - .env.prod
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  telegram-client:
    image: "thevahidal/hoopoe:${TAG}"
    command: /bin/sh -c "/home/app/web/entrypoint.prod.telegram.sh"
    restart: on-failure
    env_file:
      - .env.prod
    depends_on:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    restart: always
    image: redis:6.2
    ports:
      - "6379"
    volumes:
      - redis_data:/data
    networks:
      - local

volumes:
  redis_data:
