# Generated by Django 4.0 on 2021-12-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_organization_created_at_organization_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.CharField(max_length=128),
            preserve_default=False,
        ),
    ]
