# Generated by Django 4.0 on 2021-12-23 20:07

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_organization_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='uuid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=16, max_length=40, prefix=''),
        ),
    ]
