# Generated by Django 4.0 on 2021-12-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_drivertype_recipient_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivertype',
            name='metadata',
            field=models.JSONField(null=True),
        ),
    ]
