# Generated by Django 4.0 on 2021-12-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_organization_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='type',
            field=models.IntegerField(choices=[(0, 'EMAIL'), (0, 'TELEGRAM')], default=0),
        ),
    ]
