# Generated by Django 4.0 on 2021-12-24 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_recipient_username_alter_recipient_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='username',
            new_name='account_id',
        ),
    ]
