# Generated by Django 4.0 on 2022-03-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userprofile_created_at_userprofile_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
