# Generated by Django 4.0 on 2022-03-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_organization_name_alter_organization_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/users/recipients/%y/%m/%d/'),
        ),
    ]
