# Generated by Django 4.0 on 2022-02-28 19:49

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0013_alter_driver_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=16, max_length=40, prefix='')),
                ('message', models.TextField(blank=True, null=True)),
                ('extra', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upupas', to='users.organization')),
            ],
        ),
    ]
