# Generated by Django 4.0 on 2022-02-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upupa',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
