# Generated by Django 4.0 on 2022-02-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_upupa_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upupa',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='upupa',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
