name: Docker Image CI

on:
  #   push:
  #     branches: [ main ]
  #     tags:        
  #        - '*'     
  #   pull_request:
  #     branches: [ main ]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set tag name env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd app && docker build . --file Dockerfile.prod --tag thevahidal/hoopoe:${{ env.RELEASE_VERSION }}
    
    - name: Log into Dockerhub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/checkout@v2
    - name: Push the Docker image
      run: docker push thevahidal/hoopoe:${{ env.RELEASE_VERSION }}
